import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import { connectDB } from './config/db.js';
import scanRoutes from './routes/scanRoutes.js';
const app=express();
app.use(cors({origin:process.env.CLIENT_URL||'http://localhost:5173'}));
app.use(express.json({limit:'1mb'}));
app.get('/api/health',(req,res)=>res.json({status:'ok',service:'scamshield-server'}));
app.use('/api/scans',scanRoutes);
const port=process.env.PORT||5000;
connectDB().then(()=>app.listen(port,()=>console.log(`Server running on http://localhost:${port}`))).catch(err=>{console.error('Startup failed:',err.message);process.exit(1)});
